[package]
name = "niinii"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
imgui = { git = "https://github.com/Netdex/imgui-rs", branch = "hidpi-rounded-fix" }
# imgui-glium-renderer = { git="https://github.com/Netdex/imgui-rs", branch="hidpi-rounded-fix" }
imgui-winit-support = { git = "https://github.com/Netdex/imgui-rs", branch = "hidpi-rounded-fix" }
imgui-dx11-renderer = { git = "https://github.com/Netdex/imgui-dx11-renderer" }

[dependencies]
imgui = "0.7"
imgui-winit-support = "0.7"
clipboard = "0.5"
# imgui-glium-renderer = "0.7"
# glium = { version="0.29", default-features=true }

imgui-dx11-renderer = "0.7"
winapi = { version = "0.3", features = [
	"minwindef",
	"windef",
	"winnt",
	"winuser",
	"consoleapi",
	"libloaderapi",
	"processthreadsapi",
	"d3d9",
	"d3d9types",
	"d3dcompiler",
	"d3dcommon",
] }
wio = "0.2"
raw-window-handle = "0.3"
winit = "0.24"
detour = { version = "0.8", default-features = false }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
ichiran = { path = "third-party/ichiran" }

[lib]
name = "libniinii"
crate-type = ["cdylib"]

[workspace]
members = ["third-party/ichiran"]
