[package]
name = "niinii"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
imgui = { git="https://github.com/Netdex/imgui-rs", branch="hidpi-rounded-fix" }
imgui-glium-renderer = { git="https://github.com/Netdex/imgui-rs", branch="hidpi-rounded-fix" }
imgui-winit-support = { git="https://github.com/Netdex/imgui-rs", branch="hidpi-rounded-fix" }

[dependencies]
imgui = "0.7"
imgui-glium-renderer = "0.7"
imgui-winit-support = "0.7"
clipboard = "0.5"
glium = { version="0.29", default-features=true }

serde = { version="1", features=["derive"] }
serde_json = "1"
ichiran = { path="third-party/ichiran" }

[workspace]
members = ["third-party/ichiran"]
