[package]
name = "ichiran"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["process"] }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"

ketos = "0.12.0"
lru = "0.7.0"

log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
csv-async = { version = "1.2", features = ["tokio"] }
regex = "1"
lazy_static = "1.4.0"
strum = "0.24"
strum_macros = "0.24"

winapi = { version = "0.3", features = [
	"minwindef",
	"windef",
	"winnt",
	"winuser",
	"jobapi2",
] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
serde_path_to_error = "0.1"
