[package]
name = "ichiran"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["process"] }
futures = "0.3"
par-stream = { version = "0.10.2", features = ["runtime-tokio"] }

log = "0.4"
tracing = "0.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
csv-async = { version = "1.2", features = ["tokio"] }
regex = "1"
fancy-regex = "0.12"
lazy_static = "1.4.0"
strum = "0.25"
strum_macros = "0.25"
nonzero_ext = "0.3.0"
const_format = "0.2"
enclose = "1.1.8"
itertools = "0.12"

ketos = "0.12.0"
lru = "0.12"

winapi = { version = "0.3", features = [
	"minwindef",
	"windef",
	"winnt",
	"winuser",
	"jobapi2",
] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
serde_path_to_error = "0.1"
