[package]
name = "ichiran"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ketos = "0.12.0"
lru = "0.7.0"

log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
csv = "1.1"
regex = "1"
lazy_static = "1.4.0"
strum = "0.21"
strum_macros = "0.21"

winapi = { version = "0.3", features = [
	"minwindef",
	"windef",
	"winnt",
	"winuser",
	"jobapi2",
] }

[dev-dependencies]
serde_path_to_error = "0.1"
