[package]
name = "imgui-win32-sys"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui-sys = "0.7.0"
winapi = { version = "0.3", features = ["minwindef", "windef"] }

[build-dependencies]
cc = "1.0"
bindgen = "0.53"
