[package]
name = "openai-chat"
version = "0.1.0"
authors = ["netdex <admin@netdex.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1" }
tokio-stream = { version = "0.1", features = ["sync"] }

reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
tiktoken-rs = "0.4"

log = "0.4"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.0"
thiserror = "1"
csv = "1.1"
regex = "1"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3"
strum = "0.25"
strum_macros = "0.25"

eventsource-stream = { path = "../eventsource-stream" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
# tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
tracing-test = "0.2.4"
serde_path_to_error = "0.1"
