[package]
name = "imgui-dx11-renderer"
version = "0.12.0"
authors = ["Lukas Wirth <lukastw97@gmail.com>"]
edition = "2021"
description = "DirectX 11 renderer for the imgui crate"
homepage = "https://github.com/Veykril/imgui-dx11-renderer"
repository = "https://github.com/Veykril/imgui-dx11-renderer"
license = "MIT"
readme = "README.md"
categories = ["gui", "rendering"]

[dependencies]
winapi = { version = "0.3", features = [
    "d3d11",
    "dxgitype",
    "dxgiformat",
    "dxgi",
    "minwindef",
    "winerror",
] }
imgui = "0.12.0"
wio = "0.2"

[build-dependencies]
winapi = { version = "0.3", features = ["d3dcompiler", "d3dcommon", "winerror"] }

[dev-dependencies]
imgui-winit-support = "0.12.0"
winit = "0.29.3"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
